import { useState, useEffect } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { toast } from 'react-toastify';
import { useAuth } from '../contexts/AuthContext.jsx';
import api from '../api/axios.js';
import Header from '../components/Header.jsx';
import Footer from '../components/Footer.jsx';

const PLATFORMS = [
  { id: 'instagram', label: 'Instagram', icon: 'fab fa-instagram', color: '#E1306C', hint: 'Enter your Instagram profile URL' },
  { id: 'facebook',  label: 'Facebook',  icon: 'fab fa-facebook', color: '#1877F2', hint: 'Enter your Facebook page URL' },
  { id: 'amazon',    label: 'Amazon',    icon: 'fab fa-amazon',   color: '#FF9900', hint: 'Enter an Amazon product listing URL' },
  { id: 'flipkart',  label: 'Flipkart',  icon: 'fas fa-shopping-cart', color: '#2874F0', hint: 'Enter a Flipkart product listing URL' },
  { id: 'website',   label: 'Website',   icon: 'fas fa-globe',    color: '#00B4CC', hint: 'Enter your website URL' },
  { id: 'other',     label: 'Other',     icon: 'fas fa-link',     color: '#64748b', hint: 'Enter the URL of your online presence' },
];

const SEV_COLOR = { high: '#ef4444', medium: '#f59e0b', low: '#22c55e' };
const SEV_BG    = { high: '#fef2f2', medium: '#fffbeb', low: '#f0fdf4' };

export default function AiAudit() {
  const { user } = useAuth();
  const navigate = useNavigate();
  const [platform, setPlatform] = useState('instagram');
  const [url, setUrl] = useState('');
  const [loading, setLoading] = useState(false);
  const [report, setReport] = useState(null);
  const [freeUsed, setFreeUsed] = useState(false);
  const [checkingFree, setCheckingFree] = useState(true);
  const [unlocking, setUnlocking] = useState(false);

  const selectedPlatform = PLATFORMS.find(p => p.id === platform);

  useEffect(() => {
    if (!user) { setCheckingFree(false); return; }
    api.get('/audit/check').then(r => {
      setFreeUsed(r.data.freeAuditUsed);
    }).catch(() => {}).finally(() => setCheckingFree(false));
  }, [user]);

  const handleGenerate = async (e) => {
    e.preventDefault();
    if (!user) {
      toast.info('Please log in to generate an audit.');
      return navigate('/login?redirect=/ai-audit');
    }
    if (!url.trim()) return toast.error('Please enter a URL.');
    setLoading(true); setReport(null);
    try {
      const { data } = await api.post('/audit/generate', { platform, inputUrl: url.trim() });
      setReport(data.audit);
      setFreeUsed(true);
      if (data.isFreeAudit) toast.success('Free audit generated! Unlock the full report for ₹99.');
      else toast.success('Full audit generated!');
    } catch (err) {
      toast.error(err.response?.data?.message || 'Failed to generate audit. Try again.');
    }
    setLoading(false);
  };

  const handleUnlock = async () => {
    if (!report?._id) return;
    setUnlocking(true);
    try {
      const { data } = await api.post('/audit/unlock', {
        auditId: report._id,
        paymentId: `demo_audit_pay_${Date.now()}`,
      });
      setReport(data.audit);
      toast.success('Full report unlocked!');
    } catch (err) {
      toast.error(err.response?.data?.message || 'Could not unlock. Try again.');
    } finally {
      setUnlocking(false);
    }
  };

  const handleDownload = () => {
    if (!report) return;
    let text = `AI AUDIT REPORT\n${'═'.repeat(50)}\nPlatform: ${report.platform?.toUpperCase()}\nURL: ${report.inputUrl}\nOverall Score: ${report.report?.overallScore}/100\nDate: ${new Date(report.createdAt || Date.now()).toLocaleDateString('en-IN')}\n\nSUMMARY\n${'─'.repeat(50)}\n${report.report?.summary}\n\n`;
    report.report?.sections?.forEach(sec => {
      if (sec.locked) { text += `\n${sec.title} — LOCKED (Upgrade to view)\n`; return; }
      text += `\n${sec.title} — Score: ${sec.score}/100\n${'─'.repeat(30)}\n`;
      sec.issues?.forEach(iss => {
        text += `\n[${iss.severity?.toUpperCase()}] ${iss.title}\n${iss.description}\n→ ${iss.recommendation}\n`;
      });
    });
    text += `\n${'═'.repeat(50)}\nGenerated by Cruzen Digital AI Audit\ncruzendigital.com`;
    const blob = new Blob([text], { type: 'text/plain' });
    const a = document.createElement('a'); a.href = URL.createObjectURL(blob);
    a.download = `audit-${report.platform}-${Date.now()}.txt`; a.click();
  };

  const totalIssues = report?.report?.sections?.filter(s => !s.locked).reduce((c, s) => c + (s.issues?.length || 0), 0) || 0;
  const lockedCount = report?.report?.sections?.filter(s => s.locked).length || 0;
  const isFullyUnlocked = report && !report.report?.sections?.some(s => s.locked);

  return (
    <>
      <Header />
      <main style={{ background: '#f8fafc', minHeight: '100vh' }}>
        {/* ── Hero ── */}
        <section style={{ background: 'linear-gradient(155deg, #f0fdff 0%, #ffffff 45%, #f0fdf6 100%)', padding: '120px 20px 56px', textAlign: 'center', position: 'relative', overflow: 'hidden', borderBottom: '1px solid #e2e8f0' }}>
          {/* Dot grid */}
          <div style={{ position: 'absolute', inset: 0, backgroundImage: 'radial-gradient(circle, #00B4CC18 1px, transparent 1px)', backgroundSize: '28px 28px', opacity: 0.6 }} />
          {/* Soft blobs */}
          <div style={{ position: 'absolute', top: '-60px', right: '-60px', width: 320, height: 320, borderRadius: '50%', background: 'radial-gradient(circle, rgba(0,180,204,0.08) 0%, transparent 70%)' }} />
          <div style={{ position: 'absolute', bottom: '-40px', left: '-40px', width: 240, height: 240, borderRadius: '50%', background: 'radial-gradient(circle, rgba(29,191,115,0.07) 0%, transparent 70%)' }} />
          <div style={{ position: 'relative', zIndex: 1 }}>
            <div style={{ display: 'inline-flex', alignItems: 'center', gap: 8, background: 'rgba(0,180,204,0.1)', border: '1.5px solid rgba(0,180,204,0.25)', borderRadius: 50, padding: '6px 16px', marginBottom: 22, fontSize: '0.75rem', fontWeight: 700, color: '#0891b2', letterSpacing: '0.5px', textTransform: 'uppercase' }}>
              <i className="fas fa-robot" style={{ color: '#00B4CC' }} /> AI-Powered Audit
            </div>
            <h1 style={{ fontSize: 'clamp(2rem,5vw,3.2rem)', fontWeight: 900, margin: '0 0 16px', lineHeight: 1.1, color: '#1a1a2e' }}>
              Where Does Your Business Rank?{' '}
              <span style={{ background: 'linear-gradient(135deg,#00B4CC,#1dbf73)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', backgroundClip: 'text' }}>Find Out Free.</span>
            </h1>
            <p style={{ fontSize: '1.05rem', color: '#64748b', maxWidth: 560, margin: '0 auto 10px', lineHeight: 1.75 }}>
              Enter your Instagram, Amazon listing, Flipkart page, or website URL. Get a detailed AI audit with actionable recommendations — <strong style={{ color: '#1a1a2e' }}>first one is on us.</strong>
            </p>
          </div>
        </section>

        <div style={{ maxWidth: 960, margin: '0 auto', padding: '0 20px 80px' }}>
          {/* ── Audit Form ── */}
          <div style={{ background: '#fff', borderRadius: 20, border: '1px solid #e2e8f0', boxShadow: '0 4px 24px rgba(0,0,0,0.06)', padding: '36px', marginTop: -30, position: 'relative', zIndex: 5 }}>
            {/* Free badge */}
            {!freeUsed && user && !checkingFree && (
              <div style={{ background: 'linear-gradient(135deg, rgba(29,191,115,0.08), rgba(0,180,204,0.08))', border: '1px dashed #1dbf73', borderRadius: 12, padding: '10px 16px', marginBottom: 24, display: 'flex', alignItems: 'center', gap: 10, fontSize: '0.85rem', color: '#16a34a', fontWeight: 600 }}>
                <span style={{ fontSize: '1.2rem' }}>🎁</span> You have <strong>1 free audit</strong> available. No payment needed!
              </div>
            )}
            {freeUsed && user && !checkingFree && (
              <div style={{ background: '#fff7ed', border: '1px solid #fed7aa', borderRadius: 12, padding: '10px 16px', marginBottom: 24, display: 'flex', alignItems: 'center', gap: 10, fontSize: '0.85rem', color: '#c2410c', fontWeight: 600 }}>
                <span style={{ fontSize: '1.2rem' }}>💳</span> Free audit used. Each additional audit costs <strong>₹99</strong>.
              </div>
            )}

            <form onSubmit={handleGenerate} style={{ display: 'flex', flexDirection: 'column', gap: 24 }}>
              {/* Platform selector */}
              <div>
                <p style={{ fontWeight: 700, color: '#1a1a2e', marginBottom: 12, fontSize: '0.9rem' }}>1. Select Platform</p>
                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(130px, 1fr))', gap: 10 }}>
                  {PLATFORMS.map(p => (
                    <button key={p.id} type="button" onClick={() => setPlatform(p.id)}
                      style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 8, padding: '14px 10px', border: `2px solid ${platform === p.id ? p.color : '#e2e8f0'}`, borderRadius: 12, background: platform === p.id ? `${p.color}10` : '#fff', cursor: 'pointer', fontFamily: 'inherit', transition: 'all 0.2s' }}>
                      <i className={p.icon} style={{ fontSize: '1.4rem', color: p.color }} />
                      <span style={{ fontSize: '0.78rem', fontWeight: 600, color: platform === p.id ? p.color : '#64748b' }}>{p.label}</span>
                    </button>
                  ))}
                </div>
              </div>

              {/* URL input */}
              <div>
                <p style={{ fontWeight: 700, color: '#1a1a2e', marginBottom: 10, fontSize: '0.9rem' }}>2. Enter URL</p>
                <div style={{ display: 'flex', gap: 12 }}>
                  <div style={{ flex: 1, position: 'relative' }}>
                    <i className={`${selectedPlatform?.icon} fa-sm`} style={{ position: 'absolute', left: 14, top: '50%', transform: 'translateY(-50%)', color: selectedPlatform?.color, fontSize: '1rem' }} />
                    <input
                      type="url" value={url} onChange={e => setUrl(e.target.value)} required
                      placeholder={selectedPlatform?.hint || 'https://…'}
                      style={{ width: '100%', padding: '13px 16px 13px 42px', border: '2px solid #e2e8f0', borderRadius: 12, fontSize: '0.95rem', fontFamily: 'inherit', boxSizing: 'border-box', outline: 'none' }}
                      onFocus={e => e.target.style.borderColor = '#00B4CC'}
                      onBlur={e => e.target.style.borderColor = '#e2e8f0'}
                    />
                  </div>
                  <button type="submit" disabled={loading || !url.trim()}
                    style={{ padding: '13px 28px', background: 'linear-gradient(135deg,#00B4CC,#1dbf73)', color: '#fff', border: 'none', borderRadius: 12, fontWeight: 800, cursor: loading || !url.trim() ? 'not-allowed' : 'pointer', fontFamily: 'inherit', fontSize: '0.95rem', whiteSpace: 'nowrap', display: 'flex', alignItems: 'center', gap: 8, opacity: loading || !url.trim() ? 0.7 : 1, transition: 'opacity 0.2s' }}>
                    {loading ? <><span className="spinner-sm" />Analyzing…</> : <><i className="fas fa-search" /> Audit Now</>}
                  </button>
                </div>
                {!user && (
                  <p style={{ fontSize: '0.78rem', color: '#94a3b8', marginTop: 8 }}>
                    <i className="fas fa-info-circle" /> <Link to="/login?redirect=/ai-audit" style={{ color: '#00B4CC' }}>Log in</Link> to generate your free audit.
                  </p>
                )}
              </div>
            </form>
          </div>

          {/* ── Report ── */}
          {report && (
            <div style={{ marginTop: 32 }}>
              {/* Score header */}
              <div style={{ background: '#fff', border: '1.5px solid #e2e8f0', borderRadius: 20, padding: '24px 28px', marginBottom: 24, display: 'flex', alignItems: 'center', gap: 20, flexWrap: 'wrap', boxShadow: '0 2px 12px rgba(0,0,0,0.05)' }}>
                {/* Score ring */}
                <div style={{ width: 76, height: 76, borderRadius: '50%', background: `conic-gradient(${report.report?.overallScore >= 70 ? '#1dbf73' : report.report?.overallScore >= 50 ? '#f59e0b' : '#ef4444'} ${report.report?.overallScore * 3.6}deg, #f1f5f9 0)`, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
                  <div style={{ width: 58, height: 58, borderRadius: '50%', background: '#fff', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                    <span style={{ fontSize: '1.2rem', fontWeight: 900, color: '#1a1a2e' }}>{report.report?.overallScore}</span>
                  </div>
                </div>
                <div style={{ flex: 1 }}>
                  <div style={{ fontSize: '0.72rem', color: '#94a3b8', textTransform: 'uppercase', letterSpacing: 1, marginBottom: 4, fontWeight: 700 }}>Overall Score — {report.platform?.toUpperCase()}</div>
                  <h3 style={{ fontWeight: 800, margin: '0 0 5px', fontSize: '1.05rem', color: '#1a1a2e' }}>{report.inputUrl?.slice(0, 60)}{report.inputUrl?.length > 60 ? '…' : ''}</h3>
                  <p style={{ color: '#64748b', fontSize: '0.83rem', margin: 0, maxWidth: 480, lineHeight: 1.6 }}>{report.report?.summary}</p>
                </div>
                <div style={{ display: 'flex', gap: 10, flexShrink: 0 }}>
                  {isFullyUnlocked && (
                    <button onClick={handleDownload} style={{ padding: '9px 18px', border: '1.5px solid #e2e8f0', borderRadius: 10, background: '#f8fafc', color: '#374151', cursor: 'pointer', fontFamily: 'inherit', fontWeight: 600, fontSize: '0.82rem', display: 'flex', alignItems: 'center', gap: 7 }}>
                      <i className="fas fa-download" style={{ color: '#00B4CC' }} /> Download
                    </button>
                  )}
                  {lockedCount > 0 && (
                    <button onClick={handleUnlock} disabled={unlocking} style={{ padding: '9px 18px', background: 'linear-gradient(135deg,#00B4CC,#1dbf73)', border: 'none', borderRadius: 10, color: '#fff', cursor: 'pointer', fontFamily: 'inherit', fontWeight: 700, fontSize: '0.82rem', display: 'flex', alignItems: 'center', gap: 7 }}>
                      {unlocking ? <><span className="spinner-sm" />Processing…</> : <><i className="fas fa-lock-open" /> Unlock Full Report — ₹99</>}
                    </button>
                  )}
                </div>
              </div>

              {/* Quick stats */}
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(160px,1fr))', gap: 14, marginBottom: 24 }}>
                {[
                  { label: 'Issues Found', val: totalIssues + (lockedCount > 0 ? '+' : ''), color: '#ef4444' },
                  { label: 'Sections Analysed', val: report.report?.sections?.filter(s => !s.locked).length, color: '#00B4CC' },
                  { label: 'Sections Locked', val: lockedCount, color: '#f59e0b' },
                  { label: 'Overall Score', val: `${report.report?.overallScore}/100`, color: '#1dbf73' },
                ].map((s, i) => (
                  <div key={i} style={{ background: '#fff', border: '1px solid #e2e8f0', borderRadius: 14, padding: '18px 20px' }}>
                    <div style={{ fontSize: '1.8rem', fontWeight: 900, color: s.color }}>{s.val}</div>
                    <div style={{ fontSize: '0.72rem', color: '#94a3b8', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.5px', marginTop: 4 }}>{s.label}</div>
                  </div>
                ))}
              </div>

              {/* Section cards */}
              <div style={{ display: 'grid', gap: 16 }}>
                {report.report?.sections?.map((sec, i) => (
                  <SectionCard key={i} section={sec} index={i} onUnlock={handleUnlock} unlocking={unlocking} />
                ))}
              </div>

              {/* CTA after free */}
              {lockedCount > 0 && (
                <div style={{ background: 'linear-gradient(155deg,#f0fdff,#f0fdf6)', border: '1.5px solid #bbf7d0', borderRadius: 20, padding: '32px', marginTop: 24, textAlign: 'center' }}>
                  <div style={{ width: 52, height: 52, borderRadius: '50%', background: 'linear-gradient(135deg,#00B4CC,#1dbf73)', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 14px', fontSize: '1.3rem', color: '#fff' }}>
                    <i className="fas fa-lock-open" />
                  </div>
                  <h3 style={{ fontWeight: 800, marginBottom: 8, color: '#1a1a2e' }}>{lockedCount} section{lockedCount > 1 ? 's' : ''} locked</h3>
                  <p style={{ color: '#64748b', marginBottom: 20, maxWidth: 400, margin: '0 auto 20px', fontSize: '0.9rem', lineHeight: 1.7 }}>Unlock the complete report for just ₹99 — one-time payment, instant access, full download.</p>
                  <button onClick={handleUnlock} disabled={unlocking} style={{ padding: '13px 36px', background: 'linear-gradient(135deg,#00B4CC,#1dbf73)', border: 'none', borderRadius: 50, color: '#fff', fontWeight: 800, cursor: 'pointer', fontFamily: 'inherit', fontSize: '1rem', display: 'inline-flex', alignItems: 'center', gap: 10, boxShadow: '0 6px 20px rgba(0,180,204,0.3)' }}>
                    {unlocking ? 'Processing…' : <><i className="fas fa-lock-open" /> Unlock for ₹99</>}
                  </button>
                </div>
              )}
            </div>
          )}

          {/* ── Why audit section (when no report yet) ── */}
          {!report && !loading && (
            <div style={{ marginTop: 48 }}>
              <h2 style={{ textAlign: 'center', fontWeight: 800, color: '#1a1a2e', marginBottom: 8, fontSize: '1.5rem' }}>What You'll Get</h2>
              <p style={{ textAlign: 'center', color: '#64748b', marginBottom: 32, fontSize: '0.9rem' }}>A full report covering every aspect of your online presence</p>
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(240px,1fr))', gap: 20 }}>
                {[
                  { icon: 'fas fa-search', color: '#00B4CC', title: 'Deep Analysis', desc: 'Every aspect of your profile — bio, content, SEO, and engagement — analysed against best practices.' },
                  { icon: 'fas fa-exclamation-triangle', color: '#f59e0b', title: 'Issues by Severity', desc: 'Every issue rated High / Medium / Low so you know exactly what to fix first.' },
                  { icon: 'fas fa-lightbulb', color: '#1dbf73', title: 'Action Recommendations', desc: 'Step-by-step, implementable suggestions — not vague advice.' },
                  { icon: 'fas fa-file-download', color: '#8b5cf6', title: 'Downloadable Report', desc: 'Save your full audit report as a text file to share with your team.' },
                ].map((item, i) => (
                  <div key={i} style={{ background: '#fff', borderRadius: 16, border: '1px solid #e2e8f0', padding: '24px', textAlign: 'center' }}>
                    <div style={{ width: 52, height: 52, borderRadius: 14, background: `${item.color}15`, display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 14px', color: item.color, fontSize: '1.3rem' }}>
                      <i className={item.icon} />
                    </div>
                    <h4 style={{ fontWeight: 700, color: '#1a1a2e', marginBottom: 8 }}>{item.title}</h4>
                    <p style={{ color: '#64748b', fontSize: '0.85rem', lineHeight: 1.6, margin: 0 }}>{item.desc}</p>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      </main>
      <Footer />
    </>
  );
}

function SectionCard({ section, index, onUnlock, unlocking }) {
  const [open, setOpen] = useState(!section.locked && index < 2);

  if (section.locked) {
    return (
      <div style={{ background: '#fff', borderRadius: 16, border: '1px dashed #e2e8f0', overflow: 'hidden', position: 'relative' }}>
        {/* Blurred content behind */}
        <div style={{ filter: 'blur(4px)', pointerEvents: 'none', userSelect: 'none', padding: '20px 24px', opacity: 0.4 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 16 }}>
            <div style={{ width: 36, height: 12, background: '#e2e8f0', borderRadius: 4 }} />
            <div style={{ width: 60, height: 12, background: '#e2e8f0', borderRadius: 4 }} />
            <div style={{ marginLeft: 'auto', width: 40, height: 28, background: '#f1f5f9', borderRadius: 6 }} />
          </div>
          {[1,2,3].map(j => (
            <div key={j} style={{ background: '#f8fafc', borderRadius: 10, padding: '14px 16px', marginBottom: 10 }}>
              <div style={{ width: '60%', height: 10, background: '#e2e8f0', borderRadius: 4, marginBottom: 8 }} />
              <div style={{ width: '90%', height: 8, background: '#f1f5f9', borderRadius: 4, marginBottom: 4 }} />
              <div style={{ width: '75%', height: 8, background: '#f1f5f9', borderRadius: 4 }} />
            </div>
          ))}
        </div>
        {/* Overlay lock */}
        <div style={{ position: 'absolute', inset: 0, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', background: 'rgba(255,255,255,0.8)', backdropFilter: 'blur(2px)' }}>
          <i className="fas fa-lock" style={{ fontSize: '1.8rem', color: '#94a3b8', marginBottom: 10 }} />
          <h4 style={{ fontWeight: 700, color: '#1a1a2e', marginBottom: 6, fontSize: '1rem' }}>Section Locked</h4>
          <p style={{ color: '#64748b', fontSize: '0.82rem', marginBottom: 16, textAlign: 'center', maxWidth: 280 }}>
            This section requires the full report. Unlock all locked sections for ₹99.
          </p>
          <button onClick={onUnlock} disabled={unlocking} style={{ padding: '9px 22px', background: 'linear-gradient(135deg,#00B4CC,#1dbf73)', border: 'none', borderRadius: 10, color: '#fff', cursor: 'pointer', fontFamily: 'inherit', fontWeight: 700, fontSize: '0.85rem', display: 'flex', alignItems: 'center', gap: 7 }}>
            <i className="fas fa-lock-open" /> Unlock for ₹99
          </button>
        </div>
      </div>
    );
  }

  const scoreColor = section.score >= 70 ? '#1dbf73' : section.score >= 50 ? '#f59e0b' : '#ef4444';

  return (
    <div style={{ background: '#fff', borderRadius: 16, border: '1px solid #e2e8f0', overflow: 'hidden' }}>
      <button onClick={() => setOpen(o => !o)} style={{ width: '100%', display: 'flex', alignItems: 'center', gap: 14, padding: '18px 24px', background: 'none', border: 'none', cursor: 'pointer', fontFamily: 'inherit', textAlign: 'left' }}>
        <div style={{ width: 44, height: 44, borderRadius: '50%', background: `conic-gradient(${scoreColor} ${section.score * 3.6}deg, #f1f5f9 0)`, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
          <div style={{ width: 34, height: 34, borderRadius: '50%', background: '#fff', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            <span style={{ fontSize: '0.75rem', fontWeight: 800, color: scoreColor }}>{section.score}</span>
          </div>
        </div>
        <div style={{ flex: 1 }}>
          <h3 style={{ fontWeight: 700, color: '#1a1a2e', margin: '0 0 2px', fontSize: '0.95rem' }}>{section.title}</h3>
          <p style={{ fontSize: '0.75rem', color: '#94a3b8', margin: 0 }}>{section.issues?.length} issue{section.issues?.length !== 1 ? 's' : ''} found</p>
        </div>
        <i className={`fas fa-chevron-${open ? 'up' : 'down'}`} style={{ color: '#94a3b8', fontSize: '0.85rem' }} />
      </button>

      {open && (
        <div style={{ padding: '4px 24px 20px' }}>
          {section.issues?.map((issue, j) => (
            <div key={j} style={{ background: SEV_BG[issue.severity] || '#f8fafc', border: `1px solid ${SEV_COLOR[issue.severity] || '#e2e8f0'}22`, borderLeft: `3px solid ${SEV_COLOR[issue.severity] || '#e2e8f0'}`, borderRadius: 10, padding: '14px 16px', marginBottom: 12 }}>
              <div style={{ display: 'flex', alignItems: 'flex-start', gap: 10, marginBottom: 8 }}>
                <span style={{ background: SEV_COLOR[issue.severity], color: '#fff', fontSize: '0.65rem', fontWeight: 800, padding: '2px 8px', borderRadius: 20, textTransform: 'uppercase', flexShrink: 0, marginTop: 1 }}>{issue.severity}</span>
                <h4 style={{ fontWeight: 700, color: '#1a1a2e', margin: 0, fontSize: '0.875rem' }}>{issue.title}</h4>
              </div>
              <p style={{ color: '#64748b', fontSize: '0.82rem', margin: '0 0 8px', lineHeight: 1.6 }}>{issue.description}</p>
              <div style={{ display: 'flex', alignItems: 'flex-start', gap: 7, background: 'rgba(255,255,255,0.7)', borderRadius: 8, padding: '8px 12px' }}>
                <i className="fas fa-arrow-right" style={{ color: '#00B4CC', fontSize: '0.8rem', marginTop: 2, flexShrink: 0 }} />
                <p style={{ color: '#374151', fontSize: '0.82rem', margin: 0, lineHeight: 1.6 }}><strong>Fix:</strong> {issue.recommendation}</p>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
